# Sphinx configuration for the tt-operator documentation.
#
# Authored in MyST Markdown. Builds standalone (this repo's GitHub Pages, which
# docs.tenstorrent.com/tt-operator points at) and is also consumable by the
# docs.tenstorrent.com umbrella (tenstorrent.github.io), which injects its shared
# theme when it builds us.
import os
import shutil
from pathlib import Path

project = "TT-Operator"
copyright = "2026, Tenstorrent AI ULC"
author = "Tenstorrent"

_docs_dir = Path(__file__).resolve().parent
_repo_root = _docs_dir.parent

# -- Extensions --------------------------------------------------------------
extensions = [
    "myst_parser",
    "sphinxcontrib.mermaid",
    "sphinx_copybutton",
    "sphinx_togglebutton",
]

myst_enable_extensions = [
    "colon_fence",
    "deflist",
]
myst_heading_anchors = 3

source_suffix = {".md": "markdown", ".rst": "restructuredtext"}

# `_generated` holds the copied chart README (included, not a page); keep it out
# of the toctree so Sphinx doesn't flag it as an orphan document.
exclude_patterns = ["_build", "_generated", "Thumbs.db", ".DS_Store"]

# -- helm-docs values: render the generated chart README 1:1 -----------------
# charts/tt-operator/README.md is generated by helm-docs and kept current by the
# `docs-coherence` CI gate. Copy it into the docs tree on every build so
# configuration.md can {include} it verbatim — the values reference is always
# byte-identical to the generated chart docs, with zero manual duplication.
_chart_readme = _repo_root / "charts" / "tt-operator" / "README.md"
_generated_dir = _docs_dir / "_generated"


def _sync_chart_values(app, config):
    _generated_dir.mkdir(exist_ok=True)
    target = _generated_dir / "chart-values.md"
    if _chart_readme.is_file():
        shutil.copyfile(_chart_readme, target)
    else:
        target.write_text(
            "```{note}\n"
            "The chart values reference is unavailable in this build "
            "(the chart was not checked out).\n"
            "```\n"
        )


# -- Theme -------------------------------------------------------------------
# Use the docs.tenstorrent.com shared theme when building inside the umbrella;
# otherwise the locally-vendored Tenstorrent theme.
html_theme = "sphinx_rtd_theme"
# Match the docs.tenstorrent.com shared theme's sidebar behavior.
html_theme_options = {
    "collapse_navigation": False,
    "titles_only": True,
    "navigation_depth": 2,
}
_shared_dir = _repo_root.parent.parent / "shared"
if _shared_dir.is_dir():
    html_static_path = [str(_shared_dir / "_static"), str(_docs_dir / "_static")]
    templates_path = [str(_shared_dir / "_templates"), str(_docs_dir / "_templates")]
    html_logo = str(_shared_dir / "images" / "tt_logo.svg")
    html_favicon = str(_shared_dir / "images" / "favicon.png")
else:
    html_static_path = ["_static"]
    templates_path = ["_templates"]
    html_logo = "_static/images/tt_logo.svg"
    html_favicon = "_static/images/favicon.png"

html_title = "TT-Operator"
html_last_updated_fmt = "%b %d, %Y"

# -- Versioning --------------------------------------------------------------
# Per-release versioned site (docs/build-versions.sh builds each release tag +
# main into /<version>/). The versions widget (_templates/versions.html) reads
# these context keys; version URLs resolve at /tt-operator/<version>/.
_current_version = os.environ.get("current_version", "latest")
_versions = [v.strip() for v in os.environ.get("TT_DOCS_VERSIONS", "").splitlines() if v.strip()]
html_baseurl = f"https://docs.tenstorrent.com/tt-operator/{_current_version}/"
html_context = {
    "project_code": "tt-operator",
    "cns_component": "tt-operator",
    "versions": _versions or [_current_version],
    "current_version": _current_version,
    "logo_link_url": os.environ.get("homepage", "https://docs.tenstorrent.com/"),
    # Base URL the shared theme's search modal uses to resolve hit URLs.
    "search_site_base_url": "https://docs.tenstorrent.com/",
}


def setup(app):
    app.add_css_file("tt_theme.css")
    app.add_css_file("tt-overrides.css")
    app.connect("config-inited", _sync_chart_values)
